#[general] -> changed to root level of TOML file(do not need header [key])
live_config_reload = true

[window]
	opacity = 1.0

	startup_mode = "Maximized"
[selection]
	save_to_clipboard = true
[font]
	size = 13
    # CaskaydiaMono Nerd Font
    # JetBrainsMonoNL Nerd Font
    # the postfix "Propo" allow icons to take much space as needed f32
	normal = { family = "JetBrainsMonoNL Nerd Font Propo", style = "Regular" }

	bold = { family = "JetBrainsMonoNL Nerd Font Propo", style = "Bold" }

	italic = { family = "JetBrainsMonoNL Nerd Font Propo", style = "Italic" }

	bold_italic = { family = "JetBrainsMonoNL Nerd Font Propo", style = "Bold Italic" }
#[colors.primary]
#	background = "#000000"  #black
#
#	foreground = "#ffffff"  #white
[cursor]
	style = { shape = "Block", blinking = "Always" }

	blink_timeout = 0

	unfocused_hollow = true 
