[general]
	live_config_reload = true
[window]
	opacity = 0.85

	startup_mode = "Maximized"
[selection]
	save_to_clipboard = true
[font]
	size = 13
    # CaskaydiaMono Nerd Font
    # JetBrainsMonoNL Nerd Font
    # the postfix "Propo" allow icons to take much space as needed f32
	normal = { family = "JetBrainsMonoNL Nerd Font Propo", style = "Regular" }

	bold = { family = "JetBrainsMonoNL Nerd Font Propo", style = "Bold" }

	italic = { family = "CaskaydiaMono Nerd Font Propo", style = "Italic" }

	bold_italic = { family = "CaskaydiaMono Nerd Font Propo", style = "Bold Italic" }
[colors.primary]
	background = "#000000"  #black

	foreground = "#ffffff"  #white
#[colors.normal]
#green = "#00ff00"
#[colors.bright]
#green = "#00ff00"
[cursor]
	style = { shape = "Block", blinking = "Always" }

	blink_timeout = 0

	unfocused_hollow = true 
